<?php
//$consumerKey = 'dj0yJmk9b2dOaFRDT0FxMWVTJmQ9WVdrOVYxQjZhRWRwTlRZbWNHbzlPVEV3TkRNeE16Zy0mcz1jb25zdW1lcnNlY3JldCZ4PWRm';
//$consumerSecret = 'a1d008290f81b27747649990cdaf1809956c8a73';
$consumerKey = 'dj0yJmk9ZFVVYnNzbm1OYVFwJmQ9WVdrOVNWUndWMmRUTldVbWNHbzlPVGN3TlRZeE9ESXkmcz1jb25zdW1lcnNlY3JldCZ4PTA2';
$consumerSecret = '42ba2361f371a3093deb3f8be82effffe99f3a28';
$applicationId = 'ITpWgS5e';
?>
